### ISSUE TITLE
Crash on invalid JSON

### ISSUE THREAD

**Issue by geckom** [MC-GitFlow/personal-dictionary#6]
If you have invalid JSON then the script crashes with a stack trace.

Around line 61, update the exception handler as follows to detect this.

    try:
        criteria = json.loads("".join(open(args.file, "r").readlines()))
    except ValueError as e:
        print("Invalid JSON syntax: %s" %e)
        exit(1)
    except FileNotFoundError as e:
        print("Could not open criteria file: %s" % e)
        exit(1)

**Comment by MC-GitFlow** [comment]
Now tells when JSON file format is invalid and where the error is.
